# Generated by Django 4.2.1 on 2023-08-13 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bateria',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Batería'),
        ),
        migrations.AlterField(
            model_name='product',
            name='camara',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cámara'),
        ),
        migrations.AlterField(
            model_name='product',
            name='memoria',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Memoria'),
        ),
        migrations.AlterField(
            model_name='product',
            name='procesador',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Procesador'),
        ),
        migrations.AlterField(
            model_name='product',
            name='version',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Versión'),
        ),
    ]
