# Generated by Django 4.2.1 on 2023-08-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_product_bateria_alter_product_camara_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='precio',
            field=models.IntegerField(verbose_name='Precio'),
        ),
    ]
